theme: jekyll-theme-minimal
title: Weifan Lu
description: Welcome to Weifan's Homepage
logo: /figures/weifan_lu1.png

email: luweifan001@gamil.com
google_scholar: https://scholar.google.com/citations?user=LBrFx5gAAAAJ&hl=en
